In [2]:
#Importing numpy and training/testing split from sklearn
import numpy as np
from sklearn.model_selection import train_test_split

In [ ]:
#Creating Ts dataset

In [3]:
def make_t(top_row, left_col, stem_len):
    #top_row represents row index of the top bar (0, 1, or 2)
    #left_col represents column index of the leftmost cell of the top bar (0 or 1)
    #stem_len represents length of the stem (1, 2, or 3, but must fit the grid)

    arr = np.zeros((4, 4), dtype=int)
    #Top horizontal bar

    arr[top_row, left_col:left_col+3] = 1
    #Vertical stem (leftmost cell + length of 3 cells for the bar)

    center = left_col + 1
    #Centering stem below bar
    for i in range(1, stem_len + 1):
        arr[top_row + i, center] = 1
    return arr

In [4]:
#Creating all possible upright T configurations
all_ts = []
for r in (0, 1, 2):               #Possible rows for top bar
    for left in (0, 1):           #Alignment of leftmost cell of the bar
        max_stem = 3 - r          #longest stem that fits
        for l in range(1, max_stem + 1):
            all_ts.append(make_t(r, left, l))
print(len(all_ts))
print(all_ts)

12
[array([[1, 1, 1, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]]), array([[1, 1, 1, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 0]]), array([[1, 1, 1, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0]]), array([[0, 1, 1, 1],
       [0, 0, 1, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]]), array([[0, 1, 1, 1],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0]]), array([[0, 1, 1, 1],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0]]), array([[0, 0, 0, 0],
       [1, 1, 1, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 0]]), array([[0, 0, 0, 0],
       [1, 1, 1, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0]]), array([[0, 0, 0, 0],
       [0, 1, 1, 1],
       [0, 0, 1, 0],
       [0, 0, 0, 0]]), array([[0, 0, 0, 0],
       [0, 1, 1, 1],
       [0, 0, 1, 0],
       [0, 0, 1, 0]]), array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 1, 1, 0],
       [0, 1, 0, 0]]), array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [

In [5]:
#Choosing 100 random T configurations out of the 12 possible and storing the Ts in ts_100
indices = np.random.choice(len(all_ts), size=100, replace=True)
print(indices)
ts_100 = np.array([all_ts[i] for i in indices])

[ 3  2  8  1  0  1  7  9  6 10 11  4  1  3  3  1  7  9  7  4  3 11  2  7
  6 10  2  9  6  4  4 11  0  9  9  4  6  2  4  0  3  3  9  5  9  3  5 11
  9  2  9  6  7  2 11  2  0  9  0  1  2 10  0  4  8  9  3  9  9  9  9 11
  1 11  9  0  0  4  2  7  4  3  9  8  8  4  4  6  4  2  0  7  6  3  5  4
  3  7  6  5]


In [ ]:
#Creating Ls dataset

In [ ]:
def make_L(stem_col, start_row, stem_len, base_len):
    #The stem is vertical from (start_row, stem_col) down to (start_row+stem_len-1, stem_col)
    #The base is horizontal from (start_row+stem_len-1, stem_col) until (start_row+stem_len-1, stem_col+base_len)

    arr = np.zeros((4, 4), dtype=int)
    end_row = start_row + stem_len - 1

    #Vertical stem
    arr[start_row:end_row+1, stem_col] = 1

    #Horizontal base (includes the corner cell, which is already set)
    arr[end_row, stem_col:stem_col+base_len] = 1
    return arr

In [ ]:
#Creating all possible upright L configurations
all_Ls = []
for stem_col in range(3):          #Stem column: 0,1,2 (must leave room for base to the right)
    for start_row in range(4):      #Top of stem can be 0,1,2,3
        for stem_len in range(2, 5 - start_row):   #Stem length >=1, must fit vertically
            end_row = start_row + stem_len - 1

            #Base must have at least 2 cells (including corner) and fit to the right
            for base_len in range(2, 5 - stem_col):   #Base length >=2
                all_Ls.append(make_L(stem_col, start_row, stem_len, base_len))
print(len(all_Ls))
print(all_Ls)

36
[array([[1, 0, 0, 0],
       [1, 1, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]]), array([[1, 0, 0, 0],
       [1, 1, 1, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]]), array([[1, 0, 0, 0],
       [1, 1, 1, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0]]), array([[1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 1, 0, 0],
       [0, 0, 0, 0]]), array([[1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 1, 1, 0],
       [0, 0, 0, 0]]), array([[1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 1, 1, 1],
       [0, 0, 0, 0]]), array([[1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 1, 0, 0]]), array([[1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 1, 1, 0]]), array([[1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 1, 1, 1]]), array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 1, 0, 0],
       [0, 0, 0, 0]]), array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 1, 1, 0],
       [0, 0, 0, 0]]), array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [

In [ ]:
#Choosing 100 random L configurations out of the 36 possible and storing the Ls in ls_100
indices = np.random.choice(len(all_Ls), size=100, replace=True)
print(indices)
ls_100 = np.array([all_Ls[i] for i in indices])

[30 17 10  3  3 33 23  1 32  8 16 23 24 10 15 16 25 23  3 20 13  1 23  7
 35 24 14  8  4  4 33  8  2 35 15 27 13 10 30 16 18 34 22 30  1 20 24  1
 12  5 29 13 17 26  8  8  6  1 27 14  5 35  8 32 13 24 30  3 11  3 28 35
  0  9 19 24 26  9 15 33 35 15 16 27  4  8  0 35  3 10 22 11 33 18 20 16
 29 15  4 11]


In [ ]:
#Flattening T/Ls arrays into (n, 16) arrays
ts_100 = ts_100.reshape(-1,16)
ls_100 = ls_100.reshape(-1,16)
print(ts_100.shape)

(100, 16)


In [ ]:
#Concatenating Ts array with Ls array to create X array
#Creating y array, with 100 1s, followed by 100 0s, to correspond with the values in X array (Ts = 1 | Ls =0)
X = np.concatenate((ts_100, ls_100), axis=0)
y = np.array([1]*100 + [0]*100)
print(X.shape)
print(y.shape)

(200, 16)
(200,)


In [ ]:
print(X[:3]) #First 3 Ts

print(y[:5]) #First 5 "results" (1s for the Ts)
print(y[-5:]) #Last 5 "results" (0s for the Ls)

[[0 1 1 1 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 1 1 1 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 1 0 0 1 0]]
[1 1 1 1 1]
[0 0 0 0 0]


In [ ]:
#Creating an array of permutated indexes for the length of the X array, then applying the same shuffling/permutation to, both, the X and y array
#This shuffles the order of the inputs that the perceptron will trained/tested with, while keeping their "results" (0/1s) in a seperate, y, array with matching order to the X array.
shuffledIndices = np.random.permutation(len(X))
X = X[shuffledIndices]
y = y[shuffledIndices]

In [ ]:
print(X[:3]) #First 3 items (randomized; different from previous print results)

print(y[:5]) #First 5 "results" (randomized; different from previous print results)
print(y[-5:]) #Last 5 "results" (randomized; different from previous print results)

[[0 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0]
 [1 0 0 0 1 0 0 0 1 1 1 0 0 0 0 0]
 [1 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0]]
[0 0 0 0 1]
[0 1 0 0 1]


In [6]:
#Defining activation function, which is the Step Function
def activation_function(z):
    return np.where( z>=0, 1, 0  )

In [ ]:
def fit(X_train, y_train):

    ##################
    ## Defining the amount of "knobs" (16 weights), setting weights & bias to 0 and learning rate to 1%.
    n_features = X_train.shape[1]
    weights = np.zeros(n_features)
    bias    = 0
    learning_rate = 0.01
    #################

    for _ in range(1000):
        for idx, x_i in enumerate(X_train):

            linear_product = np.dot(x_i, weights) + bias    ## y = w*x + b   ## Inference Equation

            y_pred  = activation_function(    linear_product    ) #Predicted "result" (predicted y value, 0/1)


            update = learning_rate * ( y_pred   -  y_train[idx] )
            weights = weights - update * x_i
            bias    = bias - update
            #Updating weights & bias after each item in X_train
    return weights, bias


In [ ]:
#Printing X & y values
print(X.shape)
X[0:2, :]

(200, 16)


array([[0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0]])

In [ ]:
print(y.shape)
y

(200,)


array([0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1])

In [ ]:
X[:5, :]

array([[0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0]])

In [ ]:
#Creating training & testing split for X and y sets. Random seed definition is commented out, however, randomness is added earlier, from the 200 specifically chosen T and L variants in addition to their shuffling in the X array.  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2) #, random_state=123

In [ ]:
print( X_train.shape )
print( X_test.shape )
print( y_train.shape )
print( y_test.shape )

(160, 16)
(40, 16)
(160,)
(40,)


In [ ]:
#Training and creating weights & bias, then printing them out for use in website.
weights, bias = fit(X_train, y_train)
print(weights)
print(bias)

[ 2.00000000e-02 -1.00000000e-02  3.10000000e-01  6.00000000e-02
 -7.00000000e-02  1.70000000e-01  2.80000000e-01 -1.60000000e-01
  2.20000000e-01  9.00000000e-02  1.90000000e-01 -1.00000000e-02
 -4.00000000e-02 -3.46944695e-18  2.00000000e-01 -5.40000000e-01]
-0.46000000000000024


In [ ]:
#Defining prediction function to use trained weights & bias, as well as defining accuracy function.
def predict(X_test, weights, bias):
    ## x * w
    linear_product = np.dot(X_test, weights) + bias    ## y = w*x + b
    y_pred  = activation_function( linear_product )
    return y_pred

def accuracy(y_pred, y_true):
    accuracy = np.sum( y_pred == y_true ) / len( y_pred )
    return accuracy

In [ ]:
y_pred = predict(X_test, weights, bias)

print(y_pred)
print(y_test)
print(accuracy(y_pred,y_test))

[0 0 0 0 1 0 0 0 1 0 1 0 0 1 0 1 0 0 0 0 1 0 1 1 1 1 0 1 0 1 0 0 1 0 1 0 1
 1 1 1]
[0 0 0 0 1 0 0 0 1 0 1 0 0 1 0 1 0 0 0 0 1 0 1 1 1 1 0 1 0 1 0 0 1 0 1 0 1
 1 1 1]
1.0
